name: Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9][a-fA-F0-9]'
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          cname: giannin.ch