name: Test
on:
  push:
  workflow_call:
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
      - run: node ./testing/tests.js